### ISSUE TITLE
Zaliczenie scenariusza

### ISSUE THREAD

**Issue by krzysk1** [JacSla-dev/SimR#2]
Zauważyłem że kiedy skończę jeden scenariusz w 3_Krakowie to wszystkie się zaliczają jako ukończone (pojawia się ptaszek)- jeszcze to badam ale zgłoszę to na forum do błędów

Dotyczy to także Twojego scenariusza. Kopiując scenariusz musisz zmienić jego wewnętrzną nazwę tak aby zaliczał się niezależnie od pozostałych scenariuszy w 3_Krakowie

Zobacz wątek https://forum.simrail.eu/topic/8957-zaliczanie-scenariusza/#comment-36395

**Comment by krzysk1** [comment]
temat jeszcze potwierdzę: wykasowałem cały progres i spróbuje zaliczyć pojedyncze scenariusze sprawdzić zachowanie znacznika

**Comment by JacSla-dev** [comment]
Cześć,
Rozumiem, że wystarczy ustawić ScenarioName w manifest i nie ma potrzeby deserializować tego GUIDa? Bo jak jest w wątku napiasne 'Przejechany scenariusz jest doczepiany na podstawie GUIDa scenerii i nazwy scenariusza', czyli nawet jak GUID ten sam, to nazwa scenariusza tworzy unikalny klucz?

**Comment by krzysk1** [comment]
Błąd zaliczania scenariuszy Kraków potwierdził się i został zgłoszony już wcześniej na forum.

Sprawdziłem że np. taka zmiana w ScenarioManifest.xml rozwiązuje problem

```
  <Scenario_Name>SceneryNameText_Krk_Suw</Scenario_Name>
  (...)
      <CustomTranslation Key="SceneryNameText_Krk_Suw">
      <Translations>
        <CustomTranslationEntry LanguageTag="en">[TLK] Kraków - Suwałki</CustomTranslationEntry>	  
        <CustomTranslationEntry LanguageTag="pl">[TLK] Kraków - Suwałki</CustomTranslationEntry>
      </Translations>
    </CustomTranslation>
```

**Comment by JacSla-dev** [comment]
Spoko, ja już rano 'wpushowałem' poprawkę.
